# Starship Configuration - Managed by dottie
# https://starship.rs/config/
# Style: Similar to powerline-go with -cwd-mode semifancy -git-mode simple

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Timeout for commands executed by starship (in milliseconds)
command_timeout = 1000

# Newline at the start of the prompt
add_newline = false

# Format of the prompt - powerline-go style: ` user  path   branch âš‘  $ `
format = """$username$hostname$directory$git_branch$git_status$character"""

# Right side prompt
right_format = """$time"""

[username]
style_user = 'bold blue'
style_root = 'bold red'
format = ' [$user]($style) '
disabled = false
show_always = true

[hostname]
ssh_only = true
format = '[@$hostname](bold purple) '
disabled = false

[directory]
truncation_length = 5
truncation_symbol = 'â€¦/'
truncate_to_repo = false
format = ' [$path]($style) '
style = 'bold cyan'
read_only = ' ğŸ”’'
read_only_style = 'red'

[git_branch]
symbol = ''
format = ' [$branch]($style)'
style = 'bold green'

[git_status]
format = '[$all_status]($style) '
style = 'bold yellow'
conflicted = ' âš‘'
ahead = ' âš‘'
behind = ' âš‘'
diverged = ' âš‘'
untracked = ' âš‘'
stashed = ' âš‘'
modified = ' âš‘'
staged = ' âš‘'
renamed = ' âš‘'
deleted = ' âš‘'
up_to_date = ''

[dotnet]
format = '[$symbol($version)(ğŸ¯ $tfm)]($style) '
symbol = '.NET '
style = 'blue bold'
heuristic = true

[docker_context]
format = '[$symbol$context]($style) '
symbol = 'ğŸ³ '
style = 'blue bold'
only_with_files = true
detect_files = ['docker-compose.yml', 'docker-compose.yaml', 'Dockerfile']

[azure]
disabled = false
format = '[$symbol($subscription)]($style) '
symbol = 'ï´ƒ '
style = 'blue bold'

[kubernetes]
format = '[$symbol$context( \($namespace\))]($style) '
symbol = 'â˜¸ '
style = 'cyan bold'
disabled = false

[terraform]
format = '[$symbol$workspace]($style) '
symbol = 'ğŸ’  '
style = 'bold 105'

[cmd_duration]
min_time = 2000
format = 'took [$duration]($style) '
style = 'yellow bold'
show_milliseconds = false

[time]
disabled = false
format = '[$time]($style)'
style = 'bold dimmed white'
time_format = '%H:%M'

[character]
success_symbol = ' ï¼„'
error_symbol = ' [ï¼„](bold red)'
vimcmd_symbol = ' [ï¼„](bold green)'

[line_break]
disabled = true
